spring:
  application:
    name: invitation

  datasource:
    url: jdbc:mysql://localhost:3306/invitations
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8003


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true