server:
  port: 8000

spring:
  application:
    name: events

  datasource:
    url: jdbc:mysql://localhost:3306/events
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: deactivateGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

upload:
  location: C:\Users\ELVIS\Projects\EventConnectFiles

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
